### ISSUE TITLE
ci: run CI on node 7.6, 8 and 10

### ISSUE THREAD

**Issue by joelmukuthu** [knorm/knorm#104]
- [ ] Update Travis build to run build stages
- [ ] Ensure semantic-release is configured to run in the release build stage 
- [ ] Apply changes to all plugins

**Comment by privateOmega** [comment]
- [x]  Update Travis build to run build stages
- [x]  Ensure semantic-release is configured to run in the release build stage
- [ ]  Apply changes to all plugins
