### ISSUE TITLE
Does knorm support to sort with joined table column?

### ISSUE THREAD

**Issue by xiuqingli** [knorm/knorm#296]
In may cases, we will need to sort by joined table columns, how can we do it with knorm best practice?
if it's a missing feature, any suggestions to make a pull request? 

Thanks!

**Comment by joelmukuthu** [comment]
Yes, you can provide an `orderBy` option on the joined query:

```js
Foo.fetch({
  join: Bar.query.orderBy('id')
});
```

This returns instances of `Foo` that are actually ordered by `Bar.fields.id`.
